"""Generate the PNC VWM-cohort subject allowlist for age→VWM transfer.

Why this exists
---------------
The leakage-safe age→VWM transfer design (docs/superpowers/specs/
2026-06-13-pnc-age-vwm-transfer-design.md) requires the age "source" run and
the VWM run to operate on an *identical* subject set, so their nested-CV outer
folds match byte-for-byte — the ``SourceBackboneProvider`` alignment guard
hard-fails otherwise.

On PNC this is not automatic: ``age_at_cnb`` is near-universal (~9.5k subjects)
while ``VWM_overall_dprime`` is sparse (~1.4k), and the dataset NaN-filters on
the *current target*. So an unrestricted age run loads a much larger cohort than
the VWM run, and the two fold partitions can never coincide. (Every VWM subject
does have an age, so the VWM cohort is the binding constraint.)

This script writes the *loadable* VWM cohort — subjects that have BOTH a
connectivity graph on disk AND a non-NaN VWM score — to a ``.txt`` allowlist,
one ``sub-XXXXXXXXXX`` id per line. Pass it as
``dataset.subject_list_file=<path>`` to EVERY PNC run in this experiment
(source age, A3 from-scratch, B transfer, C concatenation) so all arms share one
cohort and one fold partition.

Carrier note: the cohort is computed with ``features=identity`` (no GLM maps
required). If a GLM-carrier arm (B3/B4) needs subjects to also have GLM maps,
regenerate with ``features=glm_diagonal`` and use that (smaller) allowlist for
those arms.

Usage
-----
    PYTHONPATH=$(pwd) .venv/bin/python scripts/make_pnc_vwm_cohort.py \
        [OUT_PATH] [LABELS] [FEATURES]

Defaults: OUT_PATH=configs/subject_lists/pnc_vwm_cohort.txt
          LABELS=pnc_VWMdprime  FEATURES=identity
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

from hydra import compose, initialize_config_dir
from omegaconf import OmegaConf

REPO_ROOT = Path(__file__).resolve().parent.parent
_SUB_RE = re.compile(r"(sub-\d+)")


def main() -> None:
    out_path = Path(sys.argv[1]) if len(sys.argv) > 1 else (
        REPO_ROOT / "configs" / "subject_lists" / "pnc_vwm_cohort.txt"
    )
    labels = sys.argv[2] if len(sys.argv) > 2 else "pnc_VWMdprime"
    features = sys.argv[3] if len(sys.argv) > 3 else "identity"

    from src.configs.dataset_config import DatasetConfig
    from src.configs.feature_config import FeatureConfig
    from src.configs.label_config import LabelConfig
    from src.datasets.registry import get_dataset

    config_dir = str(REPO_ROOT / "configs")
    with initialize_config_dir(version_base=None, config_dir=config_dir):
        cfg = compose(
            config_name="experiment",
            overrides=[f"dataset=pnc", f"labels={labels}", f"features={features}"],
        )

    dataset_cfg = DatasetConfig(**OmegaConf.to_container(cfg.dataset, resolve=True))
    feature_cfg = FeatureConfig(**OmegaConf.to_container(cfg.features, resolve=True))
    label_cfg = LabelConfig(**OmegaConf.to_container(cfg.labels, resolve=True))

    print(
        f"Loading PNC with labels={labels} (target={label_cfg.target}), "
        f"features={features} to determine the loadable cohort...",
        flush=True,
    )
    dataset = get_dataset(
        name=dataset_cfg.name, cfg=dataset_cfg,
        feature_cfg=feature_cfg, label_cfg=label_cfg,
    )
    dataset.load_raw()

    # subject_ids are "sub-XXXXXXXXXX" for single-timepoint PNC; for multi-tp
    # they are prefixed (e.g. "T0_sub-..."), so extract the bare sub-id, which
    # is what the allowlist check compares against.
    sub_ids = []
    seen = set()
    for sid in dataset._subject_ids:
        m = _SUB_RE.search(sid)
        if not m:
            continue
        bare = m.group(1)
        if bare not in seen:
            seen.add(bare)
            sub_ids.append(bare)

    sub_ids.sort()
    out_path.parent.mkdir(parents=True, exist_ok=True)
    header = (
        f"# PNC VWM cohort (target={label_cfg.target}, features={features}): "
        f"{len(sub_ids)} subjects with a graph AND a non-NaN VWM score.\n"
        f"# Generated by scripts/make_pnc_vwm_cohort.py — pass as "
        f"dataset.subject_list_file to ALL arms so folds align.\n"
    )
    out_path.write_text(header + "\n".join(sub_ids) + "\n")
    print(f"Wrote {len(sub_ids)} subject ids to {out_path}", flush=True)


if __name__ == "__main__":
    main()
